### ISSUE TITLE
[Feature Request] Automate evergreenTargets

### ISSUE THREAD

**Issue by flexyford** [pzuraq/ember-cli-babel-polyfills#13]
When using the default settings for `ember-cli-babel-polyfills`, some [modern browsers which fully support es6](https://caniuse.com/#feat=es6) do not get the polyfills they need (such as `Array.flat`) because they support `nomodule`. 

For example, let's say our app supports all browsers under `browserslist "default"` settings:

> npx browserslist 'defaults'
// ...
edge 18
// ...

Running our app in `Edge 18` the legacy polyfill is not downloaded (because `Edge 18` supports `nomodule`), however [Edge 18 did not get array#flat until version 80](https://caniuse.com/#search=flat), so Edge 18 still has `[].flat // undefined`. We would like all our target browsers to support `Array.flat`. 

---

Our team was able to programmatically filter which browsers we want in the `evergreenTargets` using the `caniuse#es6` feature. 

```js
// ember-cli-build.js
const browserslist = require('browserslist');
const caniuse = require('caniuse-api');
const cmp = require('semver-compare');
const targets = require('./config/targets');

function getSupportedBrowsersForFeature(feature, browsers = 'defaults') {
  caniuse.setBrowserScope(browsers);

  const featureSupport = caniuse.getSupport(feature);
  return browserslist(browsers).filter(target => {
    const [browser, version] = target.split(' ');
    const supportedSince = featureSupport[browser]['y'];
    return supportedSince ? cmp(version, String(supportedSince)) >= 0 : false;
  });
}

module.exports = function (defaults) {
  'ember-cli-babel-polyfills': {
      evergreenTargets: getSupportedBrowsersForFeature('es6', targets.browsers)
      // legacyTargets: defaults
    },
});
```

@pzuraq Is there any interest in updating the default `evergreenTargets` to contain all targets in `config/targets.js` which support the `es6` feature? We'd be happy to open a PR for this if others here find it useful.

**Comment by pzuraq** [comment]
Generally the recommendation with Evergreen browsers is to support a limited set of versions, for instance the last 2 versions, which is why the defaults were setup the way they are. If you need to support older versions for some reason, you can customize the targets, but I’d generally recommend against that so I think keeping the defaults to what they are is a good idea.

**Comment by flexyford** [comment]
Okay, thanks for your response. I'm curious, how would you recommend someone use `ember-cli-babel-polyfills` to support a browser like `Edge 18` which supports `nomodule`, but still requires a polyfill for something like `Array.flat`?

**Comment by pzuraq** [comment]
I would add `Edge 18` to the `evergreenTargets` setting, or add the targets you care about dynamically like you did, which seems like a good solution if you need to support that wide a range of browsers.

Is Edge 18 the release just before the Chromium change-over? Is this becoming a noticeable cliff, and preventing you from being able to specify `last 2 Edge versions` or something like that?

**Comment by flexyford** [comment]
> Is Edge 18 the release just before the Chromium change-over?

Yes it is. Edge 18 was an example of a modern browser we need to support.

Another example is Safari. We find that many of our users are bound to a version of Safari because of their MacOS operating system.  For example, a user on `OS X 10.11 El Capitan` can only have Safari up to `11.1.2 (July 9, 2018)`. [See Safari version compatibility](https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility).
Desktop safari did not get `array#flat` until version 12, so Safari 11 still has `[].flat // undefined`

This is why we've had to set `evergreenBrowsers` config dynamically, and we treat it more like a `"modernBrowsers"` config.

**Comment by pzuraq** [comment]
Sure, but I think this is really a company-specific decision in the usual case. You probably wouldn't want to support Chrome 45, or Firefox 36, because they are very good about getting their users up-to-date and encouraging that kind of behavior. The cost of supporting these older browser generally outweighs the cost of missing out on users who haven't updated.

A lot of companies have this general policy now. For instance, LinkedIn's support policy is last 2 of every major browser, and IE 11 (we don't support IE 10). We don't support Edge 18 anymore, and we don't support Safari 10. We've customized our `evergreenTargets` in usage of this addon to support those versions only, and if a user visits with an unsupported version, we let them know, since the cost is too high to continue supporting older browsers.

Edge 18 may end up becoming another cliff like IE11 I suspect, but MS has been pushing much harder to get everyone updated so I'm not so sure. I believe our support policy hasn't changed yet, and I don't think many other major companies have either. 

I'd recommend considering whether or not it's better to spend the time and effort to support these older browsers, or ask your users to update. If it's better in your case, then that's what the `evergreenBrowsers` setting exists for, as an escape hatch, and that'd be the recommended solution to this problem.

**Comment by pzuraq** [comment]
Going to close this issue for now. If it turns out that Edge 18 does become more of a sticking point in general, we can re-evaluate, but currently I don't think that's the case (and I'm hoping it doesn't become one 😬

**Comment by flexyford** [comment]
Sounds great @pzuraq, thank you. I know we'll need to support older browsers for now, but suggesting browser upgrades for our users could have benefits in due time.
